name: CI/CD Pipeline for DevSecOps Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test SonarQube Connection
        run: curl -I "${{ secrets.SONAR_HOST_URL }}/api/system/status"

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.projectKey=devsecops_edu_platform
            -Dsonar.projectName="DevSecOps Educational Website"
            -Dsonar.projectVersion=1.0.3
            -Dsonar.sources=.
            -Dsonar.language=js
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=**/test/**

  deploy:
    runs-on: ubuntu-latest
    needs: sonarqube-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the React app (bypass warnings)
        run: |
          CI=false NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy build files using sshpass + scp
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./build ./package.json ./package-lock.json ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}:"C:/Users/${{ secrets.AZURE_VM_USERNAME }}/Desktop/myapp"

      - name: SSH into Windows VM and deploy app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            powershell -Command "
              cd 'C:\Users\${{ secrets.AZURE_VM_USERNAME }}\Desktop\myapp';
              npm install;
              npm install -g serve;
              pm2 start serve --name 'cra-app' -- -s build -l 3000;
            "
